env:
  es2021: true
  jest: true
plugins:
  - eslint-plugin-node
extends: 
  - airbnb-base
  - async
  - async/node
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/extensions: off
